# Single akun
# reformat di : sub.bonds.id
# Akun Vless CF (No UDP)
# =========== PROXY ACCOUNT ===========
proxies:
  - name: REMBULANKU1 XUTS 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vmess
    uuid: bd495af4-716b-465a-8e38-10cf08ab3a12
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.do1.jstn.fun
    network: ws
    ws-opts:
      path: /104.18.214.235
      headers:
        Host: ava.game.naver.com.do1.jstn.fun
    udp: true
  - name: SG1-XUTS 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: fccdaaae-af39-41a7-9fde-fd32a48278cf
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.aio.skibidicx.web.id
    network: ws
    ws-opts:
      path: /SG1
      headers:
        Host: ava.game.naver.com.aio.skibidicx.web.id
    udp: true
  - name: SG2-XUTS 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.free.vpn-wuss.BIZ.id
    network: ws
    ws-opts:
      path: /Free/TG-at-BitzBlack/138.2.74.219-28616
      headers:
        Host: ava.game.naver.com.free.vpn-wuss.BIZ.id
    udp: true
